export const processAnalysisSchema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  title: "Teach GPT process analysis",
  type: "object",
  additionalProperties: false,
  properties: {
    schema_version: { const: 1 },
    name: { type: "string", minLength: 1, maxLength: 80 },
    description: { type: "string", minLength: 1, maxLength: 400 },
    goal: { type: "string", minLength: 1, maxLength: 400 },
    category: { type: "string", minLength: 1, maxLength: 80 },
    output_contract: {
      type: "object",
      additionalProperties: false,
      properties: {
        artifact: { type: "string" },
        success_criteria: { type: "array", items: { type: "string" } },
        equivalence_verifier: { type: "string" },
      },
      required: ["artifact", "success_criteria", "equivalence_verifier"],
    },
    inputs: { type: "array", items: { type: "string" } },
    outputs: { type: "array", items: { type: "string" } },
    software_used: { type: "array", items: { type: "string" } },
    duration_ms: { type: "integer", minimum: 0 },
    steps: {
      type: "array",
      minItems: 1,
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          order: { type: "integer", minimum: 1 },
          title: { type: "string" },
          instruction: { type: "string" },
          software: { type: "string" },
          required_capability: { type: "string" },
          approval_required: { type: "boolean" },
          verification: { type: "string" },
        },
        required: [
          "order",
          "title",
          "instruction",
          "software",
          "required_capability",
          "approval_required",
          "verification",
        ],
      },
    },
    decision_points: { type: "array", items: { type: "string" } },
    risks: { type: "array", items: { type: "string" } },
    required_capabilities: { type: "array", items: { type: "string" } },
    replayability: {
      type: "object",
      additionalProperties: false,
      properties: {
        status: {
          type: "string",
          enum: ["replayable", "assist_only", "unsupported", "unknown"],
        },
        reasons: { type: "array", items: { type: "string" } },
        missing_capabilities: { type: "array", items: { type: "string" } },
      },
      required: ["status", "reasons", "missing_capabilities"],
    },
    alternatives: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          name: { type: "string" },
          description: { type: "string" },
          changed_means: { type: "string" },
          required_capabilities: { type: "array", items: { type: "string" } },
          expected_benefit: { type: "string" },
          risks: { type: "array", items: { type: "string" } },
          equivalence_check: { type: "string" },
          verification_status: {
            type: "string",
            enum: ["verified", "testable", "unverified"],
          },
        },
        required: [
          "name",
          "description",
          "changed_means",
          "required_capabilities",
          "expected_benefit",
          "risks",
          "equivalence_check",
          "verification_status",
        ],
      },
    },
    model: { type: "string" },
    generated_at: { type: "string" },
  },
  required: [
    "schema_version",
    "name",
    "description",
    "goal",
    "category",
    "output_contract",
    "inputs",
    "outputs",
    "software_used",
    "duration_ms",
    "steps",
    "decision_points",
    "risks",
    "required_capabilities",
    "replayability",
    "alternatives",
    "model",
    "generated_at",
  ],
} as const;
